AWSTemplateFormatVersion: 2010-09-09
Description: EKS Playground - Resources for log collection

Resources:
  EKSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/eks/${AWS::StackName}-cluster/cluster
      RetentionInDays: 30
      Tags:
        - { Key: Name, Value: !Sub '/aws/eks/${AWS::StackName}-cluster/cluster' }