---
AWSTemplateFormatVersion: 2010-09-09
Description: EKS Playground - Node Group

Parameters:
  StackNamePrefix:
    Description: A prefix for the stacks in this setup.
    Type: String

Resources:

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2023_x86_64_STANDARD
      CapacityType: SPOT
      ClusterName: !Sub ${StackNamePrefix}-eks-cluster
      InstanceTypes:
        - c5.large
        - m5.large
        - r5.large
        - c6i.large
        - m6i.large
        - r6i.large
        - c7i.large
        - m7i.large
        - r7i.large
      NodeRole:
        Fn::ImportValue: !Sub ${StackNamePrefix}-base-iam-WorkerNodeInstanceRoleArn
      ScalingConfig:
        DesiredSize: 1
        MinSize: 1
        MaxSize: 4
      Subnets:
        - !ImportValue infra-vpc-sn-nat-a # private
        - !ImportValue infra-vpc-sn-nat-b # private
      Tags:
        Name: !Sub '${AWS::StackName}-NodeGroup'
