---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    app: jupyter
  namespace: default
spec:
  serviceAccountName: spark
  containers:
  - name: jupyter
    image: 000000000000.dkr.ecr.eu-north-1.amazonaws.com/spark/spark-py:jupyter-3.5.3
    imagePullPolicy: Always
    command: ['/bin/sh']
    args:
        - -c
        - >
          /opt/spark/bin/pyspark
          --master k8s://https://$KUBERNETES_PORT_443_TCP_ADDR/
          --conf spark.kubernetes.container.image=000000000000.dkr.ecr.eu-north-1.amazonaws.com/spark/spark-py:3.5.3
          --conf spark.kubernetes.container.image.pullPolicy=Always
          --conf spark.kubernetes.driver.pod.name=jupyter
          --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark
          --conf spark.driver.host=$(hostname -i)
          --conf spark.dynamicAllocation.enabled=true
          --conf spark.dynamicAllocation.shuffleTracking.enabled=true
          --conf spark.dynamicAllocation.initialExecutors=2
          --conf spark.dynamicAllocation.minExecutors=0
          --conf spark.dynamicAllocation.maxExecutors=10
          --conf spark.kubernetes.executor.request.cores=0.85
          --conf spark.executor.memory=1200M
          --conf spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.WebIdentityTokenCredentialsProvider

    resources:
      requests:
        cpu: 1.5
        memory: 3Gi
      limits:
        cpu: 2
        memory: 3Gi
